// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// col_min_idx
arma::uword col_min_idx(const arma::colvec& u, const arma::ucolvec& wlmt);
RcppExport SEXP rlt_col_min_idx(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec& >::type wlmt(wlmtSEXP);
    rcpp_result_gen = Rcpp::wrap(col_min_idx(u, wlmt));
    return rcpp_result_gen;
END_RCPP
}
// col_max_idx
arma::uword col_max_idx(const arma::colvec& u, const arma::ucolvec& wlmt);
RcppExport SEXP rlt_col_max_idx(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec& >::type wlmt(wlmtSEXP);
    rcpp_result_gen = Rcpp::wrap(col_max_idx(u, wlmt));
    return rcpp_result_gen;
END_RCPP
}
// col_min_val
double col_min_val(const arma::colvec& u, const arma::ucolvec& wlmt);
RcppExport SEXP rlt_col_min_val(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec& >::type wlmt(wlmtSEXP);
    rcpp_result_gen = Rcpp::wrap(col_min_val(u, wlmt));
    return rcpp_result_gen;
END_RCPP
}
// col_max_val
double col_max_val(const arma::colvec& u, const arma::ucolvec& wlmt);
RcppExport SEXP rlt_col_max_val(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec& >::type wlmt(wlmtSEXP);
    rcpp_result_gen = Rcpp::wrap(col_max_val(u, wlmt));
    return rcpp_result_gen;
END_RCPP
}
// col_rgn_val
double col_rgn_val(const arma::colvec& u, const arma::ucolvec& wlmt);
RcppExport SEXP rlt_col_rgn_val(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec& >::type wlmt(wlmtSEXP);
    rcpp_result_gen = Rcpp::wrap(col_rgn_val(u, wlmt));
    return rcpp_result_gen;
END_RCPP
}
// skm_gdp_val0_cpp
arma::uvec skm_gdp_val0_cpp(const arma::mat& x);
RcppExport SEXP rlt_skm_gdp_val0_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(skm_gdp_val0_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// skm_gdp_val0_mt_cpp
arma::vec skm_gdp_val0_mt_cpp(const arma::mat& x, const arma::uvec& s);
RcppExport SEXP rlt_skm_gdp_val0_mt_cpp(SEXP xSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(skm_gdp_val0_mt_cpp(x, s));
    return rcpp_result_gen;
END_RCPP
}
