# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' col_min_idx: colvec min value index within limited range
#' @param wlmt: a limit search on colvec on indices within wlmt
#' @return return an index of min value w.r.t to original index
#' @note cpp use index start from 0 vs r use index start from 1
#' @note in case of equal std:min/std:max take first index seen
col_min_idx <- function(u, wlmt) {
    .Call('rlt_col_min_idx', PACKAGE = 'rlt', u, wlmt)
}

#' col_max_idx: colvec max value index within limited range
#' @param wlmt: a limit search on colvec on indices within wlmt
#' @return return an index of max value w.r.t to original index
#' @note cpp use index start from 0 vs r use index start from 1
#' @note in case of equal std:min/std:max take first index seen
col_max_idx <- function(u, wlmt) {
    .Call('rlt_col_max_idx', PACKAGE = 'rlt', u, wlmt)
}

#' col_min_val: colvec min value within limited range
col_min_val <- function(u, wlmt) {
    .Call('rlt_col_min_val', PACKAGE = 'rlt', u, wlmt)
}

#' col_max_val: colvec max value within limited range
col_max_val <- function(u, wlmt) {
    .Call('rlt_col_max_val', PACKAGE = 'rlt', u, wlmt)
}

#' col_rgn_val: colvec range = max - min value within limited range
col_rgn_val <- function(u, wlmt) {
    .Call('rlt_col_rgn_val', PACKAGE = 'rlt', u, wlmt)
}

skm_gdp_val0_cpp <- function(x) {
    .Call('rlt_skm_gdp_val0_cpp', PACKAGE = 'rlt', x)
}

skm_gdp_val0_mt_cpp <- function(x, s) {
    .Call('rlt_skm_gdp_val0_mt_cpp', PACKAGE = 'rlt', x, s)
}

